### PR TITLE
Manipulate settings with lenses

### PR DESCRIPTION
**Pull request by johncant**
Hi @soenkehahn ,

I found that I needed to change the compiler options, so I added an argument to `initialize` and a lens so that  the configuration can be changed per route. Please forgive me if you could already somehow do this.

Cheers

### CODE REVIEW

**Comment by soenkehahn** [comment]
@johncant: I'm currently not using neither `snap` nor `haste`. Would you be interested in taking over ownership of this repo?

**Comment by johncant** [comment]
I would be honoured to maintain this repo for a while!

**Comment by soenkehahn** [comment]
@johncant: Great! You should have gotten an invite to take over the repo, I hope.

I've created a branch that allowed me to build the code on my machine: https://github.com/soenkehahn/snaplet-haste/compare/cabal_tweaks. It basically just removes upper bounds in the cabal file. But it's your decision whether to merge this now. :)

Many thanks!

**Comment by johncant** [comment]
@soenkehahn , nothing yet. I removed some of the upper bounds but didn't commit it and lost the changes. I am now in cabal hell trying to figure out what they were :fire: Yes, we should probably merge that.

**Comment by soenkehahn** [comment]
Dang, you have to remove your fork first before I can transfer ownership to you. The error message is that `johncant/snaplet-haste` already exists.

**Comment by johncant** [comment]
OK, Done.

**Comment by soenkehahn** [comment]
Now, you should've gotten an invitation. Sorry for the back and forth.

**Comment by johncant** [comment]
Still didn't get one. I've sent you a transfer request for https://github.com/johncant/test-transfer-ownership just to make sure the feature works.

**Comment by soenkehahn** [comment]
Yeah, that worked: https://github.com/soenkehahn/test-transfer-ownership.

Looking at the settings page of `snaplet-haste` it also says: `This repository is being transferred to @johncant.`. I just aborted that transfer and started it again, in hope you would get another mail.

Do you get other mails from github? Maybe your address is not set up correctly. And what about the spam folder?

I'll also transfer `test-transfer-ownership` back to you, just to see, what happens.

**Comment by johncant** [comment]
Yay, the second transfer worked! https://github.com/soenkehahn/snaplet-haste now redirects to https://github.com/johncant/snaplet-haste .

**Comment by soenkehahn** [comment]
Yay, finally. :)

Do you want me to open a PR for the cabal-upper-bounds-removal-branch?

**Comment by johncant** [comment]
Yay! :)

Nah it's cool, I just did it myself to save you the bother. My next action as "official maintainer" will be to get it into Hackage.

**Comment by soenkehahn** [comment]
:+1:

**Pull request merged**
